### PR TITLE
feat:support auto scroll when use mouse to select

### PR DESCRIPTION
**Pull request by leihaojun**
i think it is work well now.

https://github.com/user-attachments/assets/f04037d1-babb-4d3d-a767-051893b4eeef

### CODE REVIEW

**Comment by veltza** [comment]
Nice job. It works, but there are a couple of things I don't like about it.

* The text selection lags behind when the screen is scrolled. It doesn't look good and someone might think it's a bug.
* The implementation does not take borders into account. In my opinion, scrolling should start when the pointer is on the border area. This is how other terminals work. Now it only scrolls when the pointer is at the top and bottom of the window.
* I'm not a fan of the accelerated scrolling speed. The problem is that if the window is at the bottom of the screen, you can't drag the mouse any lower, and the scrolling will be really slow. The Foot terminal has the same issue. So there should be an option to disable the acceleration.

Other than that, I think your implementation is on the right track. I have a couple of ideas on how to improve it, so I'll see if I can implement them myself.

**Comment by leihaojun** [comment]
https://github.com/user-attachments/assets/56afa499-858c-42dc-965a-01872e889fb9

The text selection not lags behind when the screen is scrolled now.

**Comment by leihaojun** [comment]
now changed the trigger condition to trigger when entering the border or outside the window, so that the window can be triggered even if  window takes up the entire screen, as long as borderpx is not set to 0.


and if don't want accelerated scrolling speed.  you can just set  `autoscrolltimeout` to a A smaller value(like 1).

**Comment by veltza** [comment]
I just noticed that you created the pull request from your main branch. Don't take it personally, but I can't accept PRs from main branches (unless PR contains a simple fix). You should always create a branch for a feature or fix, then push the branch and create a PR. It's the only Github flow I'm familiar with.

So please create a new PR as this feature needs a more detailed review.

**Pull request closed without merging**
